name: cloudrun-deploy
on:
  workflow_run:
    workflows: cloudrun-test
    branches: [main, master]
    types: completed
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Publish
      if: ${{ github.event.workflow_run.conclusion == 'success' }}
      run: |
        echo "THis is the completion step of the workflow"
